### ISSUE TITLE
Bu joyda justify bermaslik yaxshi li'larni orasini margin bn ochsak yaxshi bo'lardi

### ISSUE THREAD

**Issue by Azamatjon0110** [Joxa-UZ/bookmark-landing-page#8]
![image](https://user-images.githubusercontent.com/105698184/176841168-afc1d016-5728-4738-b4ee-1361899f098d.png)

**Comment by Joxa-UZ** [comment]
Aka margin-right: 37px; dan berganman 😁. Shunchaki ul ga display: flex; berilgan vaqti justify-content ketib qolibdi aslida u yerda ishlamaydi.
